In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [3]:
# Option 1, load from sample_data if available
df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv")

In [4]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [5]:
#way of storing data
print("Print first 5 rows of the data frame")
print(df.head())

Print first 5 rows of the data frame
      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7

        b  lstat  medv
0  396.90   4.98  24.0
1  396.90   9.14  21.6
2  392.83   4.03  34.7
3  394.63   2.94  33.4
4  396.90   5.33  36.2

In [6]:
df.head(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311,15.2,386.71,17.10,18.9

In [7]:
#to access the last 5 rows of data frame
df.tail()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [8]:
df.tail(10)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
496,0.28960,0.0,9.69,0,0.585,5.390,72.9,2.7986,6,391,19.2,396.90,21.14,19.7
497,0.26838,0.0,9.69,0,0.585,5.794,70.6,2.8927,6,391,19.2,396.90,14.10,18.3
498,0.23912,0.0,9.69,0,0.585,6.019,65.3,2.4091,6,391,19.2,396.90,12.92,21.2
499,0.17783,0.0,9.69,0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [9]:
#to check basic information about the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [10]:
#to get statistical summary of the data frame
print("statistical summary of the data frame")
print(df.describe())

statistical summary of the data frame
             crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000

              age         dis         rad         tax     ptratio           b  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000

            lstat        medv
count  506.000000  506.000000
mean    12.653063   22.532806
std      7.141062    9.197104
min      1.730000    5.000000
25%      6.950000   17.025000
50%     11.360000   21.200000
75%     16.955000   25.000000
max     37.970000   50.000000

In [11]:
#missing values in the data frame  check
print('Missing values in each column:\n')
df.isnull().sum()

Missing values in each column:

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [12]:
df.drop(columns=['indus'], inplace=True)
print('Data frame after dropping the indus column:')
display(df.head())

Data frame after dropping the indus column:

,crim,zn,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [15]:
from sklearn.preprocessing import MinMaxScaler , StandardScaler, Binarizer
min_max_scaler = MinMaxScaler()

In [16]:
df_min_max_scaled = pd.DataFrame(min_max_scaler.fit_transform(df), columns=df.columns)

In [17]:
print("Data frame after Min-Max scaling:")
print(df_min_max_scaled.head())

Data frame after Min-Max scaling:
       crim    zn  chas       nox        rm       age       dis       rad  \
0  0.000000  0.18   0.0  0.314815  0.577505  0.641607  0.269203  0.000000
1  0.000236  0.00   0.0  0.172840  0.547998  0.782698  0.348962  0.043478
2  0.000236  0.00   0.0  0.172840  0.694386  0.599382  0.348962  0.043478
3  0.000293  0.00   0.0  0.150206  0.658555  0.441813  0.448545  0.086957
4  0.000705  0.00   0.0  0.150206  0.687105  0.528321  0.448545  0.086957

        tax   ptratio         b     lstat      medv
0  0.208015  0.287234  1.000000  0.089680  0.422222
1  0.104962  0.553191  1.000000  0.204470  0.368889
2  0.104962  0.553191  0.989737  0.063466  0.660000
3  0.066794  0.648936  0.994276  0.033389  0.631111
4  0.066794  0.648936  1.000000  0.099338  0.693333

In [18]:
df_min_max_scaled.describe()

,crim,zn,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,0.040544,0.113636,0.069170,0.349167,0.521869,0.676364,0.242381,0.371713,0.422208,0.622929,0.898568,0.301409,0.389618
std,0.096679,0.233225,0.253994,0.238431,0.134627,0.289896,0.191482,0.378576,0.321636,0.230313,0.230205,0.197049,0.204380
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000851,0.000000,0.000000,0.131687,0.445392,0.433831,0.088259,0.130435,0.175573,0.510638,0.945730,0.144040,0.267222
50%,0.002812,0.000000,0.000000,0.314815,0.507281,0.768280,0.188949,0.173913,0.272901,0.686170,0.986232,0.265728,0.360000
75%,0.041258,0.125000,0.000000,0.491770,0.586798,0.938980,0.369088,1.000000,0.914122,0.808511,0.998298,0.420116,0.444444
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [19]:
df.describe()
print("Statistical summary of the data frame after Min-Max scaling:")
print(df_min_max_scaled.describe())

Statistical summary of the data frame after Min-Max scaling:
             crim          zn        chas         nox          rm         age  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000
mean     0.040544    0.113636    0.069170    0.349167    0.521869    0.676364
std      0.096679    0.233225    0.253994    0.238431    0.134627    0.289896
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.000851    0.000000    0.000000    0.131687    0.445392    0.433831
50%      0.002812    0.000000    0.000000    0.314815    0.507281    0.768280
75%      0.041258    0.125000    0.000000    0.491770    0.586798    0.938980
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

              dis         rad         tax     ptratio           b       lstat  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000
mean     0.242381    0.371713    0.422208    0.622929    0.898568    0.301409
std      0.191482    0.378576    0.321636    0.230313    0.230205    0.197049
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
25%      0.088259    0.130435    0.175573    0.510638    0.945730    0.144040
50%      0.188949    0.173913    0.272901    0.686170    0.986232    0.265728
75%      0.369088    1.000000    0.914122    0.808511    0.998298    0.420116
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

             medv
count  506.000000
mean     0.389618
std      0.204380
min      0.000000
25%      0.267222
50%      0.360000
75%      0.444444
max      1.000000

In [20]:
standard_scaler = StandardScaler()
df_standard_scaled = pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)

In [21]:
print("Data frame after Standard scaling:")
print(df_standard_scaled.head())

Data frame after Standard scaling:
       crim        zn      chas       nox        rm       age       dis  \
0 -0.419782  0.284830 -0.272599 -0.144217  0.413672 -0.120013  0.140214
1 -0.417339 -0.487722 -0.272599 -0.740262  0.194274  0.367166  0.557160
2 -0.417342 -0.487722 -0.272599 -0.740262  1.282714 -0.265812  0.557160
3 -0.416750 -0.487722 -0.272599 -0.835284  1.016303 -0.809889  1.077737
4 -0.412482 -0.487722 -0.272599 -0.835284  1.228577 -0.511180  1.077737

        rad       tax   ptratio         b     lstat      medv
0 -0.982843 -0.666608 -1.459000  0.441052 -1.075562  0.159686
1 -0.867883 -0.987329 -0.303094  0.441052 -0.492439 -0.101524
2 -0.867883 -0.987329 -0.303094  0.396427 -1.208727  1.324247
3 -0.752922 -1.106115  0.113032  0.416163 -1.361517  1.182758
4 -0.752922 -1.106115  0.113032  0.441052 -1.026501  1.487503

In [22]:
df_standard_scaled.describe()

,crim,zn,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
count,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02,506.000000,5.060000e+02,5.060000e+02,5.060000e+02,5.060000e+02
mean,-1.123388e-16,7.898820e-17,-3.510587e-17,-1.965929e-16,-1.088282e-16,-1.474446e-16,-8.425408e-17,-1.123388e-16,0.000000,-4.212704e-16,-7.442444e-16,-3.089316e-16,-5.195668e-16
std,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00,1.000990,1.000990e+00,1.000990e+00,1.000990e+00,1.000990e+00
min,-4.197819e-01,-4.877224e-01,-2.725986e-01,-1.465882e+00,-3.880249e+00,-2.335437e+00,-1.267069e+00,-9.828429e-01,-1.313990,-2.707379e+00,-3.907193e+00,-1.531127e+00,-1.908226e+00
25%,-4.109696e-01,-4.877224e-01,-2.725986e-01,-9.130288e-01,-5.686303e-01,-8.374480e-01,-8.056878e-01,-6.379618e-01,-0.767576,-4.880391e-01,2.050715e-01,-7.994200e-01,-5.994557e-01
50%,-3.906665e-01,-4.877224e-01,-2.725986e-01,-1.442174e-01,-1.084655e-01,3.173816e-01,-2.793234e-01,-5.230014e-01,-0.464673,2.748590e-01,3.811865e-01,-1.812536e-01,-1.450593e-01
75%,7.396560e-03,4.877224e-02,-2.725986e-01,5.986790e-01,4.827678e-01,9.067981e-01,6.623709e-01,1.661245e+00,1.530926,8.065758e-01,4.336510e-01,6.030188e-01,2.685231e-01
max,9.933931e+00,3.804234e+00,3.668398e+00,2.732346e+00,3.555044e+00,1.117494e+00,3.960518e+00,1.661245e+00,1.798194,1.638828e+00,4.410519e-01,3.548771e+00,2.989460e+00

In [24]:
df.describe()
print("Statistical summary of the data frame after Standard scaling:")
print(df_standard_scaled.describe())

Statistical summary of the data frame after Standard scaling:
               crim            zn          chas           nox            rm  \
count  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02  5.060000e+02
mean  -1.123388e-16  7.898820e-17 -3.510587e-17 -1.965929e-16 -1.088282e-16
std    1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00  1.000990e+00
min   -4.197819e-01 -4.877224e-01 -2.725986e-01 -1.465882e+00 -3.880249e+00
25%   -4.109696e-01 -4.877224e-01 -2.725986e-01 -9.130288e-01 -5.686303e-01
50%   -3.906665e-01 -4.877224e-01 -2.725986e-01 -1.442174e-01 -1.084655e-01
75%    7.396560e-03  4.877224e-02 -2.725986e-01  5.986790e-01  4.827678e-01
max    9.933931e+00  3.804234e+00  3.668398e+00  2.732346e+00  3.555044e+00

                age           dis           rad         tax       ptratio  \
count  5.060000e+02  5.060000e+02  5.060000e+02  506.000000  5.060000e+02
mean  -1.474446e-16 -8.425408e-17 -1.123388e-16    0.000000 -4.212704e-16
std    1.000990e+00  1.000990e+00  1.000990e+00    1.000990  1.000990e+00
min   -2.335437e+00 -1.267069e+00 -9.828429e-01   -1.313990 -2.707379e+00
25%   -8.374480e-01 -8.056878e-01 -6.379618e-01   -0.767576 -4.880391e-01
50%    3.173816e-01 -2.793234e-01 -5.230014e-01   -0.464673  2.748590e-01
75%    9.067981e-01  6.623709e-01  1.661245e+00    1.530926  8.065758e-01
max    1.117494e+00  3.960518e+00  1.661245e+00    1.798194  1.638828e+00

                  b         lstat          medv
count  5.060000e+02  5.060000e+02  5.060000e+02
mean  -7.442444e-16 -3.089316e-16 -5.195668e-16
std    1.000990e+00  1.000990e+00  1.000990e+00
min   -3.907193e+00 -1.531127e+00 -1.908226e+00
25%    2.050715e-01 -7.994200e-01 -5.994557e-01
50%    3.811865e-01 -1.812536e-01 -1.450593e-01
75%    4.336510e-01  6.030188e-01  2.685231e-01
max    4.410519e-01  3.548771e+00  2.989460e+00

In [26]:
from sklearn.preprocessing import Binarizer

binarizer = Binarizer(threshold=df['medv'].mean())

df_binarized_median_house_value = pd.DataFrame(
    binarizer.fit_transform(df[['medv']]),
    columns=['median_house_value']
)

In [27]:
df['median_house_value_binarized'] = df_binarized_median_house_value['median_house_value']
print(df['median_house_value_binarized'].unique())

[1. 0.]

In [29]:
df['median_house_value_binarized'] = df_binarized_median_house_value['median_house_value']

print("Data frame after Binarization of median_house_value column:")
print(df[['medv', 'median_house_value_binarized']].head())

Data frame after Binarization of median_house_value column:
   medv  median_house_value_binarized
0  24.0                           1.0
1  21.6                           0.0
2  34.7                           1.0
3  33.4                           1.0
4  36.2                           1.0

In [31]:
print("Unique values in the binarized column:")
print(df['median_house_value_binarized'].unique())

Unique values in the binarized column:
[1. 0.]